### ISSUE TITLE
different caption for the same image

### ISSUE THREAD

**Issue by betterze** [rmokady/CLIP_prefix_caption#1]
Dear @rmokady ,

Thank you for your great work, it is very interesting.

Is there a way to generate different caption for the ame image? 

Thank you for your help.

Best Wishes,

Alex

**Comment by rmokady** [comment]
Hi @betterze,
We support two approaches to generate the images: argmax and beam-search. Note that the captions are created one token at a time where the language model output a distribution for the next token. So if you wish you can generate many captions by sample the next token out of the generated distribution instead of using argmax or beam search. Naturally, results likely to be inferior.

Hope that helps, let me know if you have additional questions.
