### ISSUE TITLE
parse_conceptual.py error

### ISSUE THREAD

**Issue by Cm744** [rmokady/CLIP_prefix_caption#18]
run parse_conceptual.py, then it ended with the following error:

NotImplementedError: There were no tensor arguments to this function (e.g., you passed an empty list of Tensors), but no fallback function is registered for schema aten::_cat.  This usually means that this function requires a non-empty list of Tensors, or that you (the operator writer) forgot to register a fallback function.  Available functions are [CPU, CUDA, QuantizedCPU, BackendSelect, Python, Named, Conjugate, Negative, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradLazy, AutogradXPU, AutogradMLC, AutogradHPU, AutogradNestedTensor, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, Tracer, UNKNOWN_TENSOR_TYPE_ID, Autocast, Batched, VmapMode].

could you please help?

**Comment by ryntwn88** [comment]
I'd recommend you review all of the paths to files or folders in your script and make sure they exist. I ran into this error because I did not have 'train' and 'val' folders created for the script to save the downloaded images to. I got the error when the script attempted to run the function create_clip_embeddings().
